[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
on_ft = 'snippet'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''

#[[plugins]]
#repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = [ 'nvim-yarp', 'vim-hug-neovim-rpc' ]
#depends = 'deoplete-jedi'
on_i = 1
hook_source = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''
'''
hook_post_source = '''
  call denite#custom#map('insert', '<Down>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<Up>', '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
#if = '!has("nvim")'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]] # python
repo = 'zchee/deoplete-jedi'
#on_ft = 'python'
on_i = 1
hook_source = '''
  let g:deoplete#sources#jedi#python_path = '/home/rtsuji005/.config/nvim/neovim3/bin/python3'
'''

#[[plugins]] # python
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#on_i = 1
#hook_add = '''
#  "jedi-vimでpreviewを表示しない
#  set completeopt-=preview
#'''

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = 'set helplang=ja,en'

