[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'Shougo/vimproc.vim'
#build = 'make'
#hook_post_update = '''
#  let cmd = 'make'
#  let g:dein#plugin.build = cmd
#'''

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'ap/vim-buftabline'
hook_add = '''
  nmap <C-n> :bn<CR>
  nmap <C-p> :bp<CR>
'''

[[plugins]] #カラースキーマ
repo = 'tomasr/molokai'
hook_add = '''
  source ~/.config/nvim/plugins/molokai.vim
'''

#[[plugins]] #カラースキーマ
#repo = 'w0ng/vim-hybrid'
#repo = 'nanotech/jellybeans.vim'
#repo = 'altercation/vim-colors-solarized'
#repo = 'vim-scripts/twilight'
#repo= 'jonathanfilip/vim-lucius'
#repo = 'vim-scripts/rdark'
#repo = 'jpo/vim-railscasts-theme'

[[plugins]] # vim-indent-guides
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  source ~/.config/nvim/plugins/indent-guides.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_path = '.*'

#[[plugins]] # python
#repo = 'vim-python/python-syntax'
#on_ft = 'python'
#hook_add = '''
#  let g:python_highlight_all = 1
#'''
#[[plugins]] # python
#repo = 'jmcantrell/vim-virtualenv'

[[plugins]] # Toml
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # markdown
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]] # markdown
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  source ~/.config/nvim/plugins/vim-markdown.vim
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'kana/vim-metarw'

[[plugins]]
repo = 'mattn/vim-metarw-gdrive'

[[plugins]]
repo = 'tyru/skk.vim'

